### ISSUE TITLE
Autocomplete data that don't match the mask

### ISSUE THREAD

**Issue by ekzGuille** [rafaelcorradini/ngx-ion-simple-mask#7]
Hi, I have a mask like this: `(+39) 000 000 000`, I've made a newPattern replacement with `{ '0': '[0-9]' }`.

During tests with the mask I noticed that if I type any number (except 3 or 9) the mask completes with `(+39) X` (where X is the typed number) but when I type 3 or 9 the mask semi-completes until the typed number. E.g: `(+3` when 3 and `(+39` when 9.

I was trying to figure out if there is any way to ignore any number except the mask.

This part of the mask is what causes the problem

```ts
if (this.mask[j] !== value[i]) {
      i--;
}
```

**Comment by rafaelcorradini** [comment]
Hi, thanks for the contributions.

We can add a flag on this statement, using a property to change the behavior.
I'll try to do that today.

**Comment by ekzGuille** [comment]
It's a pleasure.
I tried to add a new input (e.g: `sctrict :boolean`) but It turned an unexpected behaviour.

Thank you very much!
